# fly.toml app configuration file generated for la-vin-nails-app on 2023-08-28T21:22:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "la-vin-nails-app"
primary_region = "mad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
